apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demo-ingress
spec:
  rules:
  - host: nginx.bar.com
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
  - host: httpd.foo.com
    http:
      paths:
      - backend:
          serviceName: httpd
          servicePort: 80
