apiVersion: v1
kind: Service
metadata:
  name: gowiki
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: gowiki
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: gowiki
  name: gowiki
spec:
  replicas: 1
  selector:
    matchLabels:
      run: gowiki
  template:
    metadata:
      labels:
        run: gowiki
    spec:
      containers:
      - image: johscheuer/gowiki:v2
        imagePullPolicy: Always
        name: gowiki
        ports:
        - containerPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gowiki-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: gowiki
          servicePort: 8080
