apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  labels:
    app: secret-demo
spec:
  terminationGracePeriodSeconds: 0
  containers:
    - name: secret-container
      image: nginx
      env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: demo-secret
            key: username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: demo-secret
            key: password
